In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data/bigfoot.csv")

In [4]:
df

,observed,location_details,county,state,season,latitude,longitude,date,number,classification,temperature_high,temperature_mid,temperature_low,moon_phase,summary
0,"At 3:45 in the morning on Shi Shi Beach N., my...",Directions to the site: Drive through Neah Bay...,Clallam County,Washington,Summer,48.27646,-124.68020,8/25/10,28087,Class B,59.50,56.190,52.88,0.54,Foggy in the morning.
1,I was accompanied by my wife and 15-yo son. We...,"On June 22, 2020; I was parked just outside th...",Clallam County,Washington,Summer,48.11949,-124.59890,6/30/20,65667,Class B,60.57,56.820,53.07,0.35,Mostly cloudy throughout the day.
2,The sighting was the creature crossing the LaP...,NaN,Clallam County,Washington,Fall,47.94001,-124.38630,9/4/11,35409,Class A,74.21,63.425,52.64,0.25,Mostly cloudy overnight.
3,My husband was driving while we were heading n...,NaN,Grays Harbor County,Washington,Spring,47.19006,-124.19900,6/2/12,35669,Class B,57.54,52.425,47.31,0.44,Mostly cloudy throughout the day.
4,My name is Tim. My wife Nan and I live between...,The sighting occurred approximately 6.7 miles ...,Jefferson County,Washington,Winter,47.82243,-124.19500,2/25/17,57781,Class A,41.62,37.805,33.99,0.97,Foggy overnight.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,I have seen footprints of what I believe is a ...,I wish to keep this private.,York County,Maine,Winter,43.66760,-70.62350,2/27/16,51991,Class B,33.72,33.065,32.41,0.65,Clear throughout the day.
956,"Had a sighting yesterday. Oxford County, Maine...","[ 44.348740, -70.618439 ]",Oxford County,Maine,Fall,44.34113,-70.61507,9/26/20,66109,Class A,77.86,67.355,56.85,0.35,Clear throughout the day.
957,It was a picture captured on a trail camera. I...,This was taken near my property at our hunting...,Waldo County,Maine,Fall,44.69080,-69.36140,1/30/16,51005,Class B,36.03,33.830,31.63,0.71,Mostly cloudy throughout the day.
958,I was not in any way aware that these creature...,Heavily wooded wilderness miles off Route 2 in...,Penobscot County,Maine,Fall,45.04943,-68.63222,10/19/20,66224,Class B,61.23,52.425,43.62,0.13,Possible light rain overnight.
959,Background: I have spent a large part of my l...,"Spectacle Pond, West of Kingman Brook",Hancock County,Maine,Fall,44.78159,-68.22830,11/12/20,67335,Class B,58.66,45.710,32.76,0.92,Overcast throughout the day.

In [6]:
df['month']df['date']

0       8/25/10
1       6/30/20
2        9/4/11
3        6/2/12
4       2/25/17
         ...
955     2/27/16
956     9/26/20
957     1/30/16
958    10/19/20
959    11/12/20
Name: date, Length: 960, dtype: object